Implmented role logic
DADY-Solutions/HyperCafeApp pull request #3
Opened 2018-09-28 19:46 UTC by demosdemosthenous3

2018-09-29 06:59 UTC, alexyiangou commented
Good job! :+1: Very nice implementation! One comment, run `elsint` like we talked before to clean up all the syntax warnings, and see the individual comments on some lines that I commented :slightly_smiling_face:

2018-09-29 07:20 UTC, alexandrosyiangou requested changes
Good job! :+1: Very nice implementation! One comment, run `elsint` like we talked before to clean up all the syntax warnings, and see the individual comments on some lines that I commented :slightly_smiling_face:

2018-09-29 07:20 UTC, alexandrosyiangou commented on app/views/login-page/login-page.js
> +                 viewToshow = constants.customerView;
adminView maybe?

2018-09-29 07:20 UTC, alexandrosyiangou commented on app/views/login-page/login-page.js
> +           Toast.makeText("We were unable to create your account").show();
What you could also do for these 2 cases is you can try exporting the handleErrors function from the view model and use that here if it accepts the error param

2018-09-30 06:14 UTC, alexandrosyiangou approved these changes

2018-09-30 06:33 UTC, merged